// Workers have no filesystem: bake prompts/v7/*.md into a committed TS module.
// `node scripts/build-prompts.ts` writes it; `--check` fails when the committed module is stale.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const PROMPT_DIR = new URL('../prompts/v7/', import.meta.url);
export const GENERATED_PROMPTS = new URL('../apps/server/generation/prompts.generated.ts', import.meta.url);

const camel = (name: string) => name.replace(/-([a-z])/gu, (_, letter: string) => letter.toUpperCase());

/** Each file is the prompt block plus exactly one terminating newline, which is not part of the block. */
export function renderPromptsModule(dir: URL = PROMPT_DIR): string {
  const files = readdirSync(dir)
    .filter((file) => file.endsWith('.md'))
    .sort();
  const lines = files.map((file) => {
    const raw = readFileSync(new URL(file, dir), 'utf8');
    if (!raw.endsWith('\n')) throw new Error(`${file} must end with a newline`);
    return `  ${camel(file.slice(0, -3))}: ${JSON.stringify(raw.slice(0, -1))},`;
  });
  return [
    '// GENERATED by scripts/build-prompts.ts from prompts/v7/*.md. Do not edit; run `pnpm prompts:build`.',
    'export const PROMPTS_V7 = {',
    ...lines,
    '} as const;',
    '',
  ].join('\n');
}

if (import.meta.main) {
  const next = renderPromptsModule();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(GENERATED_PROMPTS, 'utf8');
    } catch {}
    if (current !== next) {
      console.error('prompts.generated.ts is stale: run `pnpm prompts:build` and commit the result.');
      process.exit(1);
    }
  } else writeFileSync(GENERATED_PROMPTS, next);
}
